src/Entity/Track.php
<?php

namespace App\Entity;

use App\Domain\Location\RegionEnum as EnumRegion;
use App\Entity\Interface\BlameableInterface;
use App\Entity\Trait\BlameableTrait;
use App\Form\Model\RejectTrack;
use App\Repository\TrackRepository;
use App\Validator\AttachmentOrUrl;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Order;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TrackRepository::class)]
#[AttachmentOrUrl]
class Track implements BlameableInterface
{
    use BlameableTrait {
        reject as protected traitReject;
    }

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\ManyToOne(targetEntity: Collective::class, fetch: 'EAGER', inversedBy: 'tracks')]
    private ?Collective $collective = null;

    #[ORM\ManyToOne(inversedBy: 'tracks')]
    private ?TrackKind $kind = null;

    /** @var Collection<int, TrackTag> */
    #[ORM\ManyToMany(targetEntity: TrackTag::class, inversedBy: 'tracks')]
    #[ORM\OrderBy(['name' => Order::Ascending->value])]
    private Collection $tags;

    /** @var Collection<int, Attachment> */
    #[ORM\OneToMany(
        targetEntity: Attachment::class,
        mappedBy: 'track',
        cascade: ['persist', 'remove'],
    )]
    private Collection $attachments;

    /** @var string[] */
    public array $attachmentsIds = [];

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?int $year = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $location = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?EnumRegion $region = null;

    public ?string $url = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isDraft = true;

    #[ORM\ManyToOne(inversedBy: 'tracks')]
    private ?User $createdBy = null;

    #[ORM\Column(nullable: true)]
    private ?bool $hasFaces = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\ManyToOne]
    private ?RejectionCause $rejectionCause = null;

    #[ORM\Column(nullable: true)]
    private ?int $creationStep = null;

    /**
     * @var Collection<int, Year>
     */
    #[ORM\ManyToMany(targetEntity: Year::class, inversedBy: 'tracks')]
    private Collection $years;

    /**
     * @var Collection<int, Region>
     */
    #[ORM\ManyToMany(targetEntity: Region::class, inversedBy: 'tracks')]
    private Collection $regions;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Attachment $coverAttachment = null;

    #[ORM\Column(length: 4095, nullable: true)]
    private ?string $rejectionMessage = null;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->attachments = new ArrayCollection();
        $this->years = new ArrayCollection();
        $this->regions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getCollectiveName(): ?string
    {
        return $this->collective?->getName();
    }

    public function getCollective(): ?Collective
    {
        return $this->collective;
    }

    public function setCollective(?Collective $collective): static
    {
        $this->collective = $collective;

        return $this;
    }

    public function getKindName(): ?string
    {
        return $this->kind?->getName();
    }

    public function getKind(): ?TrackKind
    {
        return $this->kind;
    }

    public function setKind(?TrackKind $kind): static
    {
        $this->kind = $kind;

        return $this;
    }

    public function getTagsAsString(): string
    {
        return implode(', ', $this->tags->map(fn (TrackTag $tag) => $tag->getName())->toArray());
    }

    /** @return Collection<int, TrackTag> */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(TrackTag $tag): static
    {
        if (!$this->tags->contains($tag)) {
            $this->tags->add($tag);
        }

        return $this;
    }

    public function removeTag(TrackTag $tag): static
    {
        $this->tags->removeElement($tag);

        return $this;
    }

    /** @return Collection<int, Attachment> */
    public function getAttachments(): Collection
    {
        return $this->sortAttachments();
    }

    public function addAttachment(?Attachment $attachment): static
    {
        if ($attachment && !$this->attachments->contains($attachment)) {
            $this->attachments->add($attachment);
            $attachment->setTrack($this);
        }

        return $this;
    }

    public function removeAttachment(Attachment $attachment): static
    {
        if ($this->attachments->removeElement($attachment)) {
            // set the owning side to null (unless already changed)
            if ($attachment->getTrack() === $this) {
                $attachment->setTrack(null);
            }
        }

        if ($this->coverAttachment === $attachment) {
            $this->resetCover();
        }

        return $this;
    }

    public function countAttachments(): int
    {
        return $this->attachments->count();
    }

    public function hasMultipleAttachments(): bool
    {
        return $this->countAttachments() > 1;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(?int $year): static
    {
        $this->year = $year;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function getRegionName(): ?string
    {
        return $this->region?->value;
    }

    public function getRegion(): ?EnumRegion
    {
        return $this->region;
    }

    public function setRegion(EnumRegion $region): static
    {
        $this->region = $region;

        return $this;
    }

    public function getMediaType(): ?string
    {
        if ('application/pdf' === $this->getMime()) {
            return 'pdf';
        }

        return $this->url ? 'video' : 'image';
    }

    public function isPdf(): bool
    {
        return 'pdf' === $this->getMediaType();
    }

    public function getMime(): ?string
    {
        return $this->getCover()?->getKind() ?: null;
    }

    public function isDraft(): ?bool
    {
        return $this->isDraft;
    }

    public function setDraft(?bool $isDraft): static
    {
        $this->isDraft = $isDraft;

        return $this;
    }

    public function publish(): void
    {
        $this->isDraft = false;
    }

    public function needsModeration(): bool
    {
        return !$this->isDraft && !$this->rejected && !$this->validated;
    }

    public function getPreviewUrl(): ?string
    {
        return $this->getCover()?->getPreviewUrl();
    }

    public function getVideoEmbed(): ?string
    {
        return $this->getCover()?->getVideoEmbed();
    }

    public function isVideo(): bool
    {
        return null !== $this->getPreviewUrl();
    }

    public function hasAttachments(): bool
    {
        return $this->getAttachments()->count() > 0;
    }

    public function hasFaces(): ?bool
    {
        return $this->hasFaces;
    }

    public function setHasFaces(?bool $hasFaces): static
    {
        $this->hasFaces = $hasFaces;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email ?? $this->createdBy?->getEmail();
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getContactEmail(): ?string
    {
        if ($this->createdBy?->getEmail()) {
            return $this->createdBy->getEmail();
        }

        return $this->email;
    }

    public function getRejectionCause(): ?RejectionCause
    {
        return $this->rejectionCause;
    }

    public function setRejectionCause(?RejectionCause $rejectionCause): static
    {
        $this->rejectionCause = $rejectionCause;

        return $this;
    }

    public function getCreationStep(): ?int
    {
        return $this->creationStep;
    }

    public function setCreationStep(?int $creationStep): static
    {
        $this->creationStep = $creationStep;

        return $this;
    }

    public function bumpCreationStep(?int $creationStep = 0): static
    {
        if (null === $this->creationStep || $this->creationStep < $creationStep) {
            $this->creationStep = $creationStep;
        }

        return $this;
    }

    /** @return Collection<int, Year> */
    public function getYears(): Collection
    {
        return $this->years;
    }

    public function addYear(Year $year): static
    {
        if (!$this->years->contains($year)) {
            $this->years->add($year);
        }

        return $this;
    }

    public function removeYear(Year $year): static
    {
        $this->years->removeElement($year);

        return $this;
    }

    public function getYearsAsString(): string
    {
        return implode(', ', $this->years->map(fn (Year $year) => (string) $year)->toArray());
    }

    /** @return Collection<int, Region> */
    public function getRegions(): Collection
    {
        return $this->regions;
    }

src/Controller/TrackController.php
<?php

namespace App\Controller;

use App\Domain\Search\SearchFactory;
use App\Domain\Search\SearchQueryBuilder;
use App\Domain\Search\SearchType;
use App\Domain\Search\SeenTracksManager;
use App\Domain\Track\TrackAttachmentHelper;
use App\Domain\Track\TrackPersister;
use App\Domain\Track\TrackProvider;
use App\Entity\Track;
use App\Security\Voter\Constants;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class TrackController extends AbstractController
{
    #[Route('/track', name: 'track_list', methods: ['GET', 'POST'])]
    public function index(Request $request, TrackProvider $provider, SearchFactory $factory, SeenTracksManager $seenTracksManager): Response
    {
        $search = $factory->create($request->query->all());
        $seenTracksManager->reset();
        $form = $this->createForm(SearchType::class, $search, [
            'action' => $this->generateUrl('track_search'),
        ])->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            return $this->redirectToRoute('track_list', $search->toParamsArray());
        }

        $tracks = $provider->provide($search);

        return $this->render('track/index.html.twig', ['tracks' => $tracks,  'form' => $form]);
    }

    #[Route('/track/search', name: 'track_search', methods: ['POST'])]
    public function trackSearch(Request $request, TrackProvider $provider, SearchFactory $factory, SeenTracksManager $seenTracksManager): Response
    {
        $loadMore = $request->query->getBoolean('loadMore');
        if (!$loadMore) {
            $seenTracksManager->reset();
        }
        $search = $factory->create($request->query->all(), loadMore: $loadMore);
        if (!$request->isXmlHttpRequest()) {
            return $this->redirectToRoute('track_list', $search->toParamsArray());
        }
        $this->createForm(SearchType::class, $search)->handleRequest($request);

        $tracks = $provider->provide($search);

        return $this->json([
            'html' => $this->renderView('track/components/_list.html.twig', ['tracks' => $tracks]),
            'queryParams' => $search->toParamsArray(),
            'hasNoMoreResults' => count($tracks) < SearchQueryBuilder::NUMBER_PER_PAGE,
        ]);
    }

    #[Route('/track/{id<\d+>}', name: 'track_show', methods: ['GET'])]
    public function show(Track $track): Response
    {
        return $this->render('track/show.html.twig', ['track' => $track]);
    }

    #[IsGranted(attribute: Constants::EDIT, subject: 'track')]
    #[Route('/track/{id<\d+>}/edit', name: 'track_edit', methods: ['GET'])]
    public function edit(Track $track, TrackPersister $persister): Response
    {
        $persister->markTrackFinished($track);
        $persister->updateSessionTrack($track);

        return $this->redirectToRoute('track_new', ['step' => 1]);
    }

    #[Route('/track/{id<\d+>}/regenerate_previews', name: 'track_regenerate_previews', methods: ['GET'])]
    public function regeneratePreviews(Request $request, Track $track, TrackAttachmentHelper $helper): Response
    {
        $helper->uploadMissingThumbnails($track);

        $this->addFlash('success', 'TrackPreviewRegenerated');

        $referer = $request->headers->get('referer');

        return $referer ? $this->redirect($referer) : $this->redirectToRoute('admin');
    }
}

templates/track/new/_add_media_widget.html.twig
<div class="col-12" id="select_ways_buttons">
    <div class="row">
        <div class="col-6 mt-4 d-flex">
            <div class="row flex-grow-1">
                <button type="button"
                        class="btn btn-dark btn-lg col-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3"
                        style="min-height: 100px;"
                        {{ stimulus_controller('toggle_element', {
                            showElementId: 'upload_files_container',
                            hideElementId: 'copy_video_url_container',
                            hideSecondElementId: 'select_ways_buttons',
                        })|stimulus_action('toggle_element', 'show') }}
                >
                    {{ 'ImportFile'|trans }}
                </button>
            </div>
        </div>
        <div class="col-6 mt-4 d-flex">
            <div class="row flex-grow-1 ms-2 ms-sm-0">
                <button type="button"
                        class="btn btn-dark btn-lg col-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3"
                        style="min-height: 100px;"
                        {{ stimulus_controller('toggle_element', {
                            showElementId: 'copy_video_url_container',
                            hideElementId: 'upload_files_container',
                            hideSecondElementId: 'select_ways_buttons',
                        })|stimulus_action('toggle_element', 'show') }}
                >
                    {{ 'CopyLink'|trans }}
                </button>
            </div>
        </div>
    </div>
</div>

templates/track/new/_attachments_widget.html.twig
{% set showWidget = track.hasAttachments and not track.video %}

<div class="col-12 mt-4 {{ showWidget ? '' : 'hidden' }}" id="upload_files_container">
    {{ include('components/upload/_uppy_widget.html.twig', { track }) }}
</div>

templates/track/new/_step.html.twig
{% if step == 1 %}
    {{ include('track/new/_step_1.html.twig', { form, track }) }}
{% elseif step == 2 %}
    {{ include('track/new/_step_2.html.twig', { form, track }) }}
{% elseif step == 3 %}
    {{ include('track/new/_step_3.html.twig', { form, track }) }}
{% elseif step == 4 %}
    {{ include('track/new/_step_4.html.twig', { track }) }}
{% endif %}

templates/track/new/_step_1.html.twig
<div {{ stimulus_controller('video_preview') }}>
    {{ include('track/components/_create_disclaimer.html.twig') }}
    {{ form_row(form.attachmentsIds) }}
    <div class="row text-start fs-3">
        <div class="col-12">
            {{ form_label(form.name) }}
            {{ form_widget(form.name) }}
            <div class="fs-6 mt-3">
                {{ 'ShareTrackWays'|trans }}
                <ul>
                    <li>{{ 'ShareTrackWay1'|trans }}</li>
                    <li>{{ 'ShareTrackWay2'|trans }}</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="row justify-content-end">
        {% if not track.hasAttachments %}
            {{ include('track/new/_add_media_widget.html.twig') }}
        {% endif %}
        {{ include('track/new/_attachments_widget.html.twig', {track}) }}
        {{ include('track/new/_video_widget.html.twig', {track}) }}

        <div class="col-12 col-sm-6 mt-3" id="captcha_container">
            {% if form.captcha is defined %}
                {{ form_errors(form.captcha) }}
                {{ form_widget(form.captcha) }}
            {% endif %}
        </div>
    </div>
</div>

templates/track/new/_step_2.html.twig
<div class="row d-flex align-items-start">
    <div class="col-12 col-sm-6 d-none d-sm-flex flex-column justify-content-center">
        {{ include('track/new/_step_preview.html.twig', {track, step: 2}) }}
    </div>
    <div class="col-12 col-sm-6">
        <div class="p-2">
            {{ form_widget(form.collective) }}
            {% if not track.collective %}
                {{ include('collective/create/_quick.html.twig') }}
            {% endif %}
        </div>
        <div class="p-2">{{ form_widget(form.kind) }}</div>
        <div class="p-2">{{ form_widget(form.tags) }}</div>
        <div class="p-2">{{ form_widget(form.location) }}</div>
        <div class="p-2">{{ form_widget(form.regions) }}</div>
        <div class="p-2">{{ form_widget(form.years) }}</div>

        <div {{ stimulus_controller('checkbox') }}>
            <div class="p-2 d-flex">
                <div class="flex-grow-1">{{ form_label(form.hasFaces) }}</div>
                <div class="">{{ form_widget(form.hasFaces) }}</div>
            </div>
            <div {{ stimulus_target('checkbox', 'yesContent') }} class="{{ track.hasFaces ? '' : 'hidden' }} card bg-warning p-3">
                Si des personnes réalisent une action et sont identifiables :<br/> VOUS DEVEZ FLOUTER LES VISAGES
                <br/><br/>
                Si des personnes identifiables apparaissent :<br/>
                VOUS DEVEZ AVOIR LEUR ACCORD
                OU
                VOUS DEVEZ FLOUTER LEUR VISAGE
                <div class="p-2 d-flex">
                    <div class="flex-grow-1 grotesk">{{ form_label(form.iAppliedRecommendations) }}</div>
                    <div class="">{{ form_widget(form.iAppliedRecommendations, {'attr' : {'data-checkbox-target' : 'yesConfirm'}}) }}</div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/track/new/_step_3.html.twig
<div class="row d-flex align-items-start">
    <div class="col-12 col-sm-6 d-none d-sm-flex flex-column justify-content-center">
        {{ include('track/new/_step_preview.html.twig', {track, step: 3}) }}
    </div>
    <div class="col-12 col-sm-6 pt-5">
        <div class="text-start fs-4">{{ form_label(form.description) }}</div>
        <div class="text-start fs-4 plaine">{{ form_help(form.description) }}</div>
        {{ form_widget(form.description) }}

        {% if not is_granted('ROLE_USER') %}
            <div class="mt-2 text-start">
                {{ 'ConfirmCreationLeaveEmail'|trans }}
                {{ form_widget(form.email) }}
            </div>
        {% endif %}
    </div>
</div>

templates/track/new/_step_4.html.twig
<div class="text-dark h-100 p-2 flex-column">
    <div class="p-4 pt-0">
        <div class="row">
            <div class="col-12 col-sm-7 d-none d-sm-flex flex-column justify-content-center">
                {{ include('track/new/_step_preview.html.twig', {track, showInformation: false, step: 4}) }}
            </div>
            <div class="col-12 col-sm-5 text-start">
                {{ include('track/components/_information_rows.html.twig', {track}) }}

                {% if track.contactEmail is not null %}
                    <div class="alert alert-primary rounded-0 mt-4">
                        <span class="fs-6"><i class="fa fa-envelope me-2"></i>{{ 'PublishDisclaimer'|trans }}</span>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

templates/track/new/_step_preview.html.twig
{% set showInformation = showInformation is defined ? showInformation : true %}
{% if track.attachments|length > 1 %}
    <div class="p-2">
        <a class="btn btn-light" href="{{ path('track_update_cover', {id: track.id, step}) }}">{{ 'UpdateCover'|trans }}</a>
    </div>
{% endif %}
{{ include('track/components/glider/_glider.html.twig', {track}) }}
{% if showInformation %}
    <div class="col-12 text-start">
        {{ include('track/components/_information_rows.html.twig', {track}) }}
    </div>
{% endif %}

templates/track/new/_video_widget.html.twig
<div class="col-12 col-sm-6 mt-4 {{ track.video ? '' : 'hidden' }}" id="copy_video_url_container">
    <h5>{{ 'CopyResourceLink'|trans }}</h5>
    {{ form_widget(form.url, {attr: {
        'data-video-preview-target': 'input',
        'data-action': 'video-preview#preview',
    }}) }}
    <div class="w-100 mt-3 d-none" {{ stimulus_target('video-preview', 'previewFailureDisclaimer') }}>
        <div class="alert alert-warning">
            <i class="fa fa-info-circle me-2"></i>
            {{ 'VideoPreviewGenerationFailed'|trans }}
        </div>
    </div>
    <img src="{{ track.previewUrl ?: '' }}"
         class="w-100 mt-3"
         alt=""
        {{ stimulus_target('video-preview', 'preview') }}
         style="max-width: 300px"
    />
</div>

templates/track/new/disclaimer.html.twig
{% extends 'templates/card_page.html.twig' %}

{% block title %}{{ 'DropNewTrack'|trans }}{% endblock %}

{% block cardContent %}
    <div>
        <div class="border-1 p-3">
            <p class="lead">
            Les traces sont la mémoire vivante du mouvement des Gilets jaunes. Venez les découvrir
                <a target="_blank" href="{{ path('track_new') }}">ici !</a>
            </p>
        </div>
    </div>

    <div class="p-3">
        <p>Vous avez deux options :</p>
        <p>
            > Soyez autonomes et allez-y ! Nous vous conseillons de créer un compte, c’est rapide et
            facile, et cela vous permettra d’accéder à vos traces et de les modifier si besoin.
            Pour créer un compte ou vous connecter, c’est
            <a target="_blank" href="{{ path('app_login') }}">ici !</a>
        </p>
        <p>
            > <a target="_blank" href="{{ path('support_us') }}">Contactez-nous</a>
            si vous
            préférez être accompagné.e dans cette démarche.
        </p>
        <br/>
        <p>C’est à vous de jouer !</p>
    </div>
    <div class="p-3 text-center">
        <a href="{{ path('track_new') }}" class="btn-lg btn btn-primary">{{ 'LetsGo'|trans }}</a>
    </div>
{% endblock %}

templates/track/new/index.html.twig
{% extends 'track/new/step_template.html.twig' %}

{% block step %}{{ step }}{% endblock %}

{% block innerContent %}
    {{ form_start(form, { attr: {
        class: 'h-100 d-flex flex-column',
        'data-controller': 'autosubmit',
        'data-autosubmit-target': 'form',
        'data-autosubmit-url-value': path('track_new', { step }),
    } } ) }}
        {{ form_errors(form) }}
        <div class="flex-grow-1">
            {{ include('track/new/_step.html.twig', { form, track, step }) }}
        </div>
        {{ include('track/components/form/_prev_next_buttons.html.twig', { form, track, step }) }}
        {{ form_widget(form._token) }}
    {{ form_end(form, {'render_rest': false}) }}
{% endblock %}

templates/track/new/step_template.html.twig
{% extends 'templates/base.html.twig' %}

{% block title %}{{ 'CreateTrack'|trans }}{% endblock %}
{% block bodybg %}primary{% endblock %}
{% set step = block('step') %}

{% block javascripts %}
    <script src=" https://cdn.jsdelivr.net/npm/swiper@11.2.8/swiper-bundle.min.js "></script>
    {{ parent() }}
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
    {{ parent() }}
{% endblock %}

{% block alerts %}{% endblock %}

{% block content %}
    <div class="h-100 text-dark d-flex flex-column">
        <h3 class="mt-5">{{ 'ShareArchive'|trans }} <span class="d-sm-none">{{ step }}/4</span></h3>
        <h4 class="d-none d-sm-block">{{ step }}/4</h4>
        {{ include('track/components/_breadcrumb.html.twig', {
            maxStep: track.creationStep,
            currentStep: step,
            steps: constant('App\\Form\\TrackType::STEPS') })
        }}
        {{ include('components/_alerts.html.twig') }}
        <div class="col-12 p-3 pt-0 flex-grow-1">
            {% block innerContent %}
            {% endblock %}
        </div>
    </div>
{% endblock %}

templates/track/new/update_preview.html.twig
{% extends 'templates/card_page.html.twig' %}

{% block title %}{{ 'UpdateCover'|trans }}{% endblock%}
{% block bodybg %}primary{% endblock %}

{% block cardContent %}
        <div class="row d-flex justify-content-center">
            {% for attachment in track.attachments %}
                {% set thumbUrl = get_thumb_url(attachment) %}
                {% set isCover = track.cover == attachment %}
                <div class="col mt-2 d-flex justify-content-center flex-column align-items-center">
                    <a class="btn btn-link" href="{{ path('track_update_cover', {id: track.id, newCoverId: attachment.id, step}) }}">
                        <div
                            class="img-thumbnail thumbnail position-relative {{ isCover ? 'border border-4 border-primary' : '' }}"
                            style="background-image: url('{{ thumbUrl }}');"></div>
                    </a>
                </div>
            {% endfor %}
        </div>
        <div class="text-end mt-2">
            <a class="btn btn-primary" href="{{ path('track_new', {step}) }}">
                {{ 'ResumeCreation'|trans }}
            </a>
        </div>
{% endblock %}